### ISSUE TITLE
Submission of milstone2

### ISSUE THREAD

**Issue by PANDASANG1231** [UBC-MDS/datasci_salaries_py#20]
Check readme and everthing else and submit

**Comment by artanzand** [comment]
For milestone 3:
[]Submission - Artan
[]Peer Review - Josh, Wenjia
[]Comparing technologies - Artan, Doris
Python:
[]Dockerfile (copy from https://github.com/flor14/532-ia1-flordandrea/blob/master/Dockerfile) - Wenjia
[]Add favicon and title- Artan
R:
[]Individual plots - Individual
