### ISSUE TITLE
Feats: Individual plot-Joshua

### ISSUE THREAD

**Issue by PANDASANG1231** [UBC-MDS/datasci_salaries_py#25]
Individual plot by Joshua

**Comment by joshsia** [comment]
The plot to create the histogram for a specific country is [here](https://github.com/joshsia/datasci-salaries-dashboard/blob/main/app/app.py).

<img width="502" alt="hist-country" src="https://user-images.githubusercontent.com/56477506/156071652-869d3b06-7673-4fa7-8657-687ac5eebadd.png">

**Comment by joshsia** [comment]
Let me know if any changes need to be made!
