### ISSUE TITLE
Feats: Individual plot-Artan

### ISSUE THREAD

**Issue by PANDASANG1231** [UBC-MDS/datasci_salaries_py#26]
Individual plot Artan

**Comment by joshsia** [comment]
As discussed in our meeting, we will link the code to the scripts used in our individual assignments where we have created the plots, so that Artan can add them to this repo easily. @artanzand @SiqiTao @PANDASANG1231

**Comment by joshsia** [comment]
For the histogram of a specific country, see [here](https://github.com/joshsia/datasci-salaries-dashboard/blob/main/app/app.py).

<img width="502" alt="hist-country" src="https://user-images.githubusercontent.com/56477506/156071500-02e05f65-66f7-4f13-9ccb-264d1e86cb26.png">

**Comment by artanzand** [comment]
Here is the link to my repo with salary plots:
https://github.com/artanzand/DS_salaries_dash/blob/main/app.py

And this is what it looks like:
https://dsci532-2022-ia1-artan.herokuapp.com/

**Comment by joshsia** [comment]
Currently in `plot.py`, we have the lines
```
df = df.query("Salary_USD < 400_000")
df = df[df["Tenure"] != "I don't write code to analyze data"]
```
but I'm not sure why the data was filtered this way.

Also, in the scatter plot, the feature `Tenure` was renamed as `Coding Experience` which is confusing.
