### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by artanzand** [UBC-MDS/datasci_salaries_py#78]
Improvements:
1. Artan - Sort highest paying countries based on median: https://github.com/UBC-MDS/datasci_salaries_py/commit/0c00e84ea5a9e6a75352aabe2cdc95565d992497
2. Josh - Replacing education_level with remote_work in the histogram: https://github.com/UBC-MDS/datasci_salaries_py/commit/9428e83d255d1971c0c2d2ee92170a42f7848f7b
3. Josh - Make salary range vertical for heatmap: https://github.com/UBC-MDS/datasci_salaries_py/commit/0f2eff919979d5ff52e87fdf421c14d7a25c289a
4. Josh - Add top 5 highest paying countries (median): https://github.com/UBC-MDS/datasci_salaries_py/commit/1725ba74190e6333723e2261d29b8e754094e2fb
5. Artan - Make the dropdown title of sidebar more intuitive: https://github.com/UBC-MDS/datasci_salaries_py/commit/24cc469f1121bfa109635c4aa1ac391e736d97ab

**Comment by joshsia** [comment]
After our meeting on 17 March, the remaining tasks to do are:
- Move salary range slider below dropdown menu where we choose a country
- Make salary range slider affect all the country-specific plots
- Remove boxplot legend

**Comment by joshsia** [comment]
All the proposed changes have been implemented.
